import { Inter } from "next/font/google";
import "./globals.css";

// bootstrap
import "bootstrap/dist/css/bootstrap.min.css";
import Container from "./components/bootstrap-components/Container";
import TopNav from "./components/bootstrap-components/navbar/TopNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "MY Blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-bs-theme="dark">
      <body className={inter.className}>
        <Container>
          <TopNav />
          {children}
        </Container>
      </body>
    </html>
  );
}
